title: Jesús Adolfo Parra Parra
email: jesus@adolfoparra.com.ve
description:
  es: Una página personal
  en: A personal webpage
copyright:
  es: Todos los derechos reservados.
  en: All rights reserved.
age: 24
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adolfoparra.com.ve" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zargex

timezone: America/Montreal
exclude: ['temas_interesantes.txt', '/blog']
paginate: 5
#sidebar_blog_link:  '/blog' 
#paginate_path: '/blog/page:num'

# Build settings
keep_files: ['.git', 'CNAME']
markdown: kramdown
#theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-polyglot
    
# Language settings
languages: ["en","es"]
default_lang: "en"
exclude_from_localization: ["images", "pdf", "css", "certificates_files"]

# Collections
collections:
  certificates_files:
